version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: studydb
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "23307:3307"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    build:
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studydb
      TZ: "Asia/Tokyo"
